version: '3'
services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "33060:3306"
    volumes:
      - ./master.cnf:/etc/mysql/conf.d/mysql.cnf
    restart: always

  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "33061:3306"
    volumes:
      - ./slave.cnf:/etc/mysql/conf.d/mysql.cnf
    restart: always

  #mysql-router:
  #  image: mysql/mysql-router:8.0.23
  #  container_name: mysql-router
  #  environment:
  #    MYSQL_HOST: "mysql-master"
  #    MYSQL_PORT: "3306"
  #    MYSQL_USER: root
  #    MYSQL_PASSWORD: password
  #  ports:
  #    - "6446:6446"
  #  restart: always


  